AWSTemplateFormatVersion: '2010-09-09'
Description: Implantacao de um Plano de Backup do AWS Backup

Parameters:
  VaultName:
    Description: Nome do Vault para armazenar os Backups (Padrao Nome-EC2, Nome-EKS, Nome-RDS)
    Type: String
    Default: ""

  NewVaultName:
    Description: Criar novo Vault?
    Type: String
    Default: Nao
    AllowedValues:
      - Sim
      - Nao

  BackupPlanName:
    Description: Nome do plano de backup
    Type: String
    Default: ""

  CronMinute:
    Description: Minuto de inicio(0-59)minutos
    Type: String
    Default: "0"

  CronHour:
    Description: Hora de inicio(0-23)horas
    Type: String
    Default: "0"

  CronDay:
    Description: Dia do mes (1-30 ou 1-31)
    Type: String
    Default: "?"

  CronMonth:
    Description: Mes (1-12)
    Type: String
    Default: "*"

  CronDayOfWeek:
    Description: Dia da semana (MON, TUE, WED, THU, FRI, SAT, SUN). Aceita mais de um valor separado por ,
    Type: CommaDelimitedList
    Default: "*"
    AllowedValues:
    - MON
    - TUE
    - WED
    - THU
    - FRI
    - SAT
    - SUN
    - "*"
  CronYear:
    Description: Ano (2023, 2024 por exemplo)
    Type: String
    Default: "*"

  DiaRetencao:
    Description: Quantidade de dias que o backup sera retido no Vault (30, 60, etc)
    Type: String
    Default: 30

Conditions:
  CreateBackupVault: !Equals [!Ref NewVaultName, "Sim"]

  # Define um plano de backup do AWS Backup
Resources:
  BackupVault:
    Type: 'AWS::Backup::BackupVault'
    Condition: CreateBackupVault
    Properties:
      BackupVaultName: !Ref VaultName

  BackupPlan1:
    Type: 'AWS::Backup::BackupPlan'
    Properties:
      BackupPlan:
        BackupPlanName: !Ref BackupPlanName
        BackupPlanRule:
          - RuleName: BackupDiario
            TargetBackupVault:
              Fn::If:
                - CreateBackupVault
                - !Ref BackupVault
                - !Ref VaultName
            ScheduleExpression: !Join 
              - ''
              - - cron(
                - !Ref CronMinute
                - ' '
                - !Ref CronHour
                - ' '
                - !Ref CronDay
                - ' '
                - !Ref CronMonth
                - ' '
                - !Join 
                  - ','
                  - !Ref CronDayOfWeek
                - ' '
                - !Ref CronYear
                - )
            Lifecycle:
              DeleteAfterDays: 30
              
Outputs:
  BackupVaultName:
    Value: !Ref VaultName
    Description: Nome do Vault de Backup

  BackupPlanId:
    Value: !Ref BackupPlan1
    Description: ID do Plano de Backup
